package com.caglar.finalprojectaws.Views;

import com.caglar.finalprojectaws.Controllers.Student;
import com.caglar.finalprojectaws.Controllers.Controllers;
import com.caglar.finalprojectaws.Controllers.Teacher;
import static com.caglar.finalprojectaws.ValidationAndMethod.ValidationAndCalculation.*;
import com.caglar.finalprojectaws.Views.*;
import java.awt.Color;

/**
 *
 * @author cagla
 */
public class AdminFrame extends javax.swing.JFrame {

    Controllers connect = new Controllers();

    Student s1 = new Student();
    Teacher t1 = new Teacher();

    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        studentTeacherLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        studentSearchBTN = new javax.swing.JButton();
        teacherSearchBTN = new javax.swing.JButton();
        addNewStudentBTN = new javax.swing.JButton();
        addNewTeacherBTN = new javax.swing.JButton();
        inactiveStudentBTN = new javax.swing.JButton();
        logoHeadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Frame");

        adminPanel.setBackground(new java.awt.Color(239, 240, 234));

        studentTeacherLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        studentTeacherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentTeacherLabel.setText("Student or Teacher ID");
        studentTeacherLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentTeacherLabel.setPreferredSize(new java.awt.Dimension(160, 30));

        idTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        idTF.setPreferredSize(new java.awt.Dimension(160, 30));
        idTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTFFocusLost(evt);
            }
        });
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTFKeyTyped(evt);
            }
        });

        studentSearchBTN.setBackground(new java.awt.Color(0, 153, 153));
        studentSearchBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        studentSearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        studentSearchBTN.setText("Student Info");
        studentSearchBTN.setPreferredSize(new java.awt.Dimension(100, 30));
        studentSearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentSearchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentSearchBTNMouseExited(evt);
            }
        });
        studentSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchBTNActionPerformed(evt);
            }
        });

        teacherSearchBTN.setBackground(new java.awt.Color(0, 153, 153));
        teacherSearchBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        teacherSearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        teacherSearchBTN.setText("Teacher Info");
        teacherSearchBTN.setPreferredSize(new java.awt.Dimension(100, 30));
        teacherSearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherSearchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherSearchBTNMouseExited(evt);
            }
        });
        teacherSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSearchBTNActionPerformed(evt);
            }
        });

        addNewStudentBTN.setBackground(new java.awt.Color(0, 153, 153));
        addNewStudentBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addNewStudentBTN.setForeground(new java.awt.Color(255, 255, 255));
        addNewStudentBTN.setText("Add New Student");
        addNewStudentBTN.setPreferredSize(new java.awt.Dimension(100, 30));
        addNewStudentBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewStudentBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewStudentBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addNewStudentBTNMousePressed(evt);
            }
        });
        addNewStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudentBTNActionPerformed(evt);
            }
        });

        addNewTeacherBTN.setBackground(new java.awt.Color(0, 153, 153));
        addNewTeacherBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addNewTeacherBTN.setForeground(new java.awt.Color(255, 255, 255));
        addNewTeacherBTN.setText("Add New Teacher");
        addNewTeacherBTN.setPreferredSize(new java.awt.Dimension(100, 30));
        addNewTeacherBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewTeacherBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewTeacherBTNMouseExited(evt);
            }
        });
        addNewTeacherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTeacherBTNActionPerformed(evt);
            }
        });

        inactiveStudentBTN.setBackground(new java.awt.Color(0, 153, 153));
        inactiveStudentBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        inactiveStudentBTN.setForeground(new java.awt.Color(255, 255, 255));
        inactiveStudentBTN.setText("Inactive Student");
        inactiveStudentBTN.setEnabled(false);
        inactiveStudentBTN.setPreferredSize(new java.awt.Dimension(100, 30));
        inactiveStudentBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inactiveStudentBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inactiveStudentBTNMouseExited(evt);
            }
        });
        inactiveStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactiveStudentBTNActionPerformed(evt);
            }
        });

        logoHeadingLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        logoHeadingLabel.setForeground(new java.awt.Color(0, 0, 0));
        logoHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoHeadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/caglar/finalprojectaws/Images/gti-logo.png"))); // NOI18N
        logoHeadingLabel.setText("Record-Keeping System Further Education College");
        logoHeadingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoHeadingLabel.setIconTextGap(8);
        logoHeadingLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentTeacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoHeadingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentSearchBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewStudentBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 50, Short.MAX_VALUE)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherSearchBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewTeacherBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(idTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inactiveStudentBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoHeadingLabel)
                .addGap(18, 18, 18)
                .addComponent(studentTeacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherSearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentSearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewTeacherBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inactiveStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentSearchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentSearchBTNMouseEntered
        studentSearchBTN.setBackground(new Color(0, 204, 204));
        studentSearchBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_studentSearchBTNMouseEntered

    private void studentSearchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentSearchBTNMouseExited
        studentSearchBTN.setBackground(new Color(0, 153, 153));
        studentSearchBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_studentSearchBTNMouseExited

    private void studentSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchBTNActionPerformed
        s1.setStudent_id(idTF.getText().toString());
        StudentInfoFrame sif = new StudentInfoFrame(s1);
        sif.setVisible(true);
    }//GEN-LAST:event_studentSearchBTNActionPerformed

    private void idTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTFFocusGained
        idTF.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_idTFFocusGained

    private void idTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTFFocusLost
        idTF.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_idTFFocusLost

    private void teacherSearchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherSearchBTNMouseEntered
        teacherSearchBTN.setBackground(new Color(0, 204, 204));
        teacherSearchBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_teacherSearchBTNMouseEntered

    private void teacherSearchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherSearchBTNMouseExited
        teacherSearchBTN.setBackground(new Color(0, 153, 153));
        teacherSearchBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_teacherSearchBTNMouseExited

    private void teacherSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSearchBTNActionPerformed
        t1.setTeacher_id(idTF.getText().toString());
        TeacherInfoFrame tif = new TeacherInfoFrame(t1);
        tif.setVisible(true);
    }//GEN-LAST:event_teacherSearchBTNActionPerformed

    private void addNewStudentBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStudentBTNMouseEntered
        addNewStudentBTN.setBackground(new Color(0, 204, 204));
        addNewStudentBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_addNewStudentBTNMouseEntered

    private void addNewStudentBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStudentBTNMouseExited
        addNewStudentBTN.setBackground(new Color(0, 153, 153));
        addNewStudentBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addNewStudentBTNMouseExited

    private void addNewStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudentBTNActionPerformed
        NewStudent student = new NewStudent();
        student.setVisible(true);
    }//GEN-LAST:event_addNewStudentBTNActionPerformed

    private void addNewTeacherBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewTeacherBTNMouseEntered
        addNewTeacherBTN.setBackground(new Color(0, 204, 204));
        addNewTeacherBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_addNewTeacherBTNMouseEntered

    private void addNewTeacherBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewTeacherBTNMouseExited
        addNewTeacherBTN.setBackground(new Color(0, 153, 153));
        addNewTeacherBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addNewTeacherBTNMouseExited

    private void addNewTeacherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTeacherBTNActionPerformed
        NewTeacher teacher = new NewTeacher();
        teacher.setVisible(true);
    }//GEN-LAST:event_addNewTeacherBTNActionPerformed

    private void inactiveStudentBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inactiveStudentBTNMouseEntered
        inactiveStudentBTN.setBackground(new Color(0, 204, 204));
        inactiveStudentBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_inactiveStudentBTNMouseEntered

    private void inactiveStudentBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inactiveStudentBTNMouseExited
        inactiveStudentBTN.setBackground(new Color(0, 153, 153));
        inactiveStudentBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_inactiveStudentBTNMouseExited

    private void inactiveStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactiveStudentBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inactiveStudentBTNActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void addNewStudentBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStudentBTNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewStudentBTNMousePressed

    private void idTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyTyped
       DigitValidation(evt);
    }//GEN-LAST:event_idTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewStudentBTN;
    private javax.swing.JButton addNewTeacherBTN;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton inactiveStudentBTN;
    private javax.swing.JLabel logoHeadingLabel;
    private javax.swing.JButton studentSearchBTN;
    private javax.swing.JLabel studentTeacherLabel;
    private javax.swing.JButton teacherSearchBTN;
    // End of variables declaration//GEN-END:variables
}
