package com.caglar.finalprojectaws.Views;

import com.caglar.finalprojectaws.Controllers.Controllers;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import static com.caglar.finalprojectaws.ValidationAndMethod.ValidationAndCalculation.*;

public class NewStudent extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement prest;
    private Statement st;
    Controllers connect = new Controllers();

    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudentPanel = new javax.swing.JPanel();
        personalInfoPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        classCodeLabel = new javax.swing.JLabel();
        ppsnLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        classCodeTF = new javax.swing.JTextField();
        ppsnTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        dobTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        adminIdTF = new javax.swing.JTextField();
        contactDetailsPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        addressLineOneLabel = new javax.swing.JLabel();
        addressLineTwo = new javax.swing.JLabel();
        eircodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        addressLineOneTF = new javax.swing.JTextField();
        addressLineTwoTF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        eircodeTF = new javax.swing.JTextField();
        addNewStudentBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Student Frame");

        newStudentPanel.setBackground(new java.awt.Color(239, 240, 234));

        personalInfoPanel.setBackground(new java.awt.Color(239, 240, 234));
        personalInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Info"));

        firstNameLabel.setText("First Name");
        firstNameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        surnameLabel.setText("Surname");
        surnameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        classCodeLabel.setText("Class Code");
        classCodeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        ppsnLabel.setText("PPSN");
        ppsnLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        genderLabel.setText("Gender");
        genderLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        dobLabel.setText("Date of Birth");
        dobLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        firstNameTF.setPreferredSize(new java.awt.Dimension(200, 30));
        firstNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTFKeyTyped(evt);
            }
        });

        surnameTF.setPreferredSize(new java.awt.Dimension(200, 30));
        surnameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnameTFKeyTyped(evt);
            }
        });

        classCodeTF.setPreferredSize(new java.awt.Dimension(200, 30));
        classCodeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                classCodeTFKeyTyped(evt);
            }
        });

        ppsnTF.setPreferredSize(new java.awt.Dimension(200, 30));
        ppsnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppsnTFKeyTyped(evt);
            }
        });

        genderTF.setPreferredSize(new java.awt.Dimension(200, 30));
        genderTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genderTFKeyTyped(evt);
            }
        });

        dobTF.setPreferredSize(new java.awt.Dimension(200, 30));
        dobTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobTFKeyTyped(evt);
            }
        });

        jLabel1.setText("Admin ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));

        adminIdTF.setPreferredSize(new java.awt.Dimension(200, 30));
        adminIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIdTFActionPerformed(evt);
            }
        });
        adminIdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adminIdTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(adminIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ppsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ppsnTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        contactDetailsPanel.setBackground(new java.awt.Color(239, 240, 234));
        contactDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));

        emailLabel.setText("E-mail");
        emailLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        phoneNumberLabel.setText("Phone Number");
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        addressLineOneLabel.setText("Address Line One");
        addressLineOneLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        addressLineTwo.setText("Address Line Two");
        addressLineTwo.setPreferredSize(new java.awt.Dimension(100, 30));

        eircodeLabel.setText("Eircode");
        eircodeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        cityLabel.setText("City");
        cityLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        emailTF.setPreferredSize(new java.awt.Dimension(300, 30));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });
        emailTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTFKeyTyped(evt);
            }
        });

        phoneNumberTF.setPreferredSize(new java.awt.Dimension(300, 30));
        phoneNumberTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberTFKeyTyped(evt);
            }
        });

        addressLineOneTF.setPreferredSize(new java.awt.Dimension(300, 30));
        addressLineOneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressLineOneTFKeyTyped(evt);
            }
        });

        addressLineTwoTF.setPreferredSize(new java.awt.Dimension(300, 30));
        addressLineTwoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressLineTwoTFKeyTyped(evt);
            }
        });

        cityTF.setPreferredSize(new java.awt.Dimension(300, 30));
        cityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityTFKeyTyped(evt);
            }
        });

        eircodeTF.setPreferredSize(new java.awt.Dimension(300, 30));
        eircodeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eircodeTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout contactDetailsPanelLayout = new javax.swing.GroupLayout(contactDetailsPanel);
        contactDetailsPanel.setLayout(contactDetailsPanelLayout);
        contactDetailsPanelLayout.setHorizontalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(addressLineTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(addressLineOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(eircodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eircodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        contactDetailsPanelLayout.setVerticalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(addressLineOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressLineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addressLineTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressLineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eircodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eircodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addNewStudentBTN.setBackground(new java.awt.Color(0, 153, 153));
        addNewStudentBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addNewStudentBTN.setForeground(new java.awt.Color(255, 255, 255));
        addNewStudentBTN.setText("Add New Student");
        addNewStudentBTN.setPreferredSize(new java.awt.Dimension(449, 23));
        addNewStudentBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewStudentBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewStudentBTNMouseExited(evt);
            }
        });
        addNewStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudentBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newStudentPanelLayout = new javax.swing.GroupLayout(newStudentPanel);
        newStudentPanel.setLayout(newStudentPanelLayout);
        newStudentPanelLayout.setHorizontalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(contactDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addComponent(addNewStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        newStudentPanelLayout.setVerticalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addComponent(contactDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNewStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(newStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void addNewStudentBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStudentBTNMouseEntered
        addNewStudentBTN.setBackground(new Color(0, 204, 204));
        addNewStudentBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_addNewStudentBTNMouseEntered

    private void addNewStudentBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStudentBTNMouseExited
        addNewStudentBTN.setBackground(new Color(0, 153, 153));
        addNewStudentBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addNewStudentBTNMouseExited

    private void addNewStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudentBTNActionPerformed
        String adminId = adminIdTF.getText().toString();
        if (!(firstNameTF.getText().toString().isEmpty() || surnameTF.getText().toString().isEmpty())) {
        connect.addNewStudent(adminId, classCodeTF, firstNameTF, surnameTF, ppsnTF, genderTF,
                emailTF, phoneNumberTF, addressLineOneTF, addressLineTwoTF, cityTF, eircodeTF, dobTF);
            } else {
            DisplayMessage("Fill at least first name and sur name");
        }
    }//GEN-LAST:event_addNewStudentBTNActionPerformed

    private void adminIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminIdTFActionPerformed

    private void firstNameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_firstNameTFKeyTyped

    private void surnameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_surnameTFKeyTyped

    private void genderTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_genderTFKeyTyped

    private void emailTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTFKeyTyped
        emailValidation(evt, emailTF);
    }//GEN-LAST:event_emailTFKeyTyped

    private void phoneNumberTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberTFKeyTyped
        DigitValidation(evt);
    }//GEN-LAST:event_phoneNumberTFKeyTyped

    private void ppsnTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppsnTFKeyTyped
        LetterOrDigitValidation(evt);
    }//GEN-LAST:event_ppsnTFKeyTyped

    private void dobTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobTFKeyTyped
        dateValidation(evt);
    }//GEN-LAST:event_dobTFKeyTyped

    private void adminIdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminIdTFKeyTyped
        DigitValidation(evt);
    }//GEN-LAST:event_adminIdTFKeyTyped

    private void addressLineOneTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressLineOneTFKeyTyped
        LetterOrDigitOrSpaceValidation(evt);
    }//GEN-LAST:event_addressLineOneTFKeyTyped

    private void addressLineTwoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressLineTwoTFKeyTyped
        LetterOrDigitOrSpaceValidation(evt);
    }//GEN-LAST:event_addressLineTwoTFKeyTyped

    private void cityTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_cityTFKeyTyped

    private void eircodeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eircodeTFKeyTyped
        LetterOrDigitOrSpaceValidation(evt);
    }//GEN-LAST:event_eircodeTFKeyTyped

    private void classCodeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classCodeTFKeyTyped
        LetterOrDigitValidation(evt);
    }//GEN-LAST:event_classCodeTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewStudentBTN;
    private javax.swing.JLabel addressLineOneLabel;
    private javax.swing.JTextField addressLineOneTF;
    private javax.swing.JLabel addressLineTwo;
    private javax.swing.JTextField addressLineTwoTF;
    private javax.swing.JTextField adminIdTF;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTF;
    private javax.swing.JLabel classCodeLabel;
    private javax.swing.JTextField classCodeTF;
    private javax.swing.JPanel contactDetailsPanel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel eircodeLabel;
    private javax.swing.JTextField eircodeTF;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel newStudentPanel;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTF;
    private javax.swing.JLabel ppsnLabel;
    private javax.swing.JTextField ppsnTF;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTF;
    // End of variables declaration//GEN-END:variables
}
