package com.caglar.finalprojectaws.Views;

import com.caglar.finalprojectaws.Controllers.Student;
import com.caglar.finalprojectaws.Controllers.Controllers;
import static com.caglar.finalprojectaws.ValidationAndMethod.ValidationAndCalculation.*;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

public class TeacherFrame extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement prest;
    private Statement st;
    Controllers connect = new Controllers();
    


    public void clearCB() {
        gradeOneTF.setText("");
        gradeTwoTF.setText("");
        gradeThreeTF.setText("");
        finalExamTF.setText("");
        resultTF.setText("");
    }

    public void clearSearchBTN() {
        fullnameTF.setText("");
        gradeOneTF.setText("");
        gradeTwoTF.setText("");
        gradeThreeTF.setText("");
        finalExamTF.setText("");
        resultTF.setText("");
    }

    public TeacherFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherPanel = new javax.swing.JPanel();
        updateGradeBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        subjectCB = new javax.swing.JComboBox<>();
        firstGradeLabel = new javax.swing.JLabel();
        secondGradeLabel = new javax.swing.JLabel();
        thirdGradeLabel = new javax.swing.JLabel();
        finalExamLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        gradeOneTF = new javax.swing.JTextField();
        gradeTwoTF = new javax.swing.JTextField();
        gradeThreeTF = new javax.swing.JTextField();
        finalExamTF = new javax.swing.JTextField();
        resultTF = new javax.swing.JTextField();
        logoHeadingLabel = new javax.swing.JLabel();
        studentIDLabel = new javax.swing.JLabel();
        studentIDTF = new javax.swing.JTextField();
        warningLabel = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        fullnameLabel = new javax.swing.JLabel();
        fullnameTF = new javax.swing.JTextField();
        studenInfoBTN = new javax.swing.JButton();
        classGroupFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Frame");
        setBounds(new java.awt.Rectangle(800, 100, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        teacherPanel.setBackground(new java.awt.Color(239, 240, 234));

        updateGradeBTN.setBackground(new java.awt.Color(0, 153, 153));
        updateGradeBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        updateGradeBTN.setForeground(new java.awt.Color(255, 255, 255));
        updateGradeBTN.setText("Add / Update Grade");
        updateGradeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateGradeBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateGradeBTNMouseExited(evt);
            }
        });
        updateGradeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGradeBTNActionPerformed(evt);
            }
        });

        deleteBTN.setBackground(new java.awt.Color(0, 153, 153));
        deleteBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(255, 255, 255));
        deleteBTN.setText("Delete Grade");
        deleteBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBTNMouseExited(evt);
            }
        });
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        subjectCB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        subjectCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6N0736 - Graphical User Interface Programming", "6N2108 - Object Oriented Programming", "6N4785 - Relational Database", "6N4090 - Project Management", "6N0734 - Mobile Technologies ", "6N1449 - Software Architecture", "6N1946 - Work Experience", "6N3395 - Mathematics", "6N2191 - Leadership" }));
        subjectCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCBActionPerformed(evt);
            }
        });

        firstGradeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        firstGradeLabel.setText("First Grade");
        firstGradeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        secondGradeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        secondGradeLabel.setText("Second Grade");
        secondGradeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        thirdGradeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        thirdGradeLabel.setText("Third Grade");
        thirdGradeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        finalExamLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        finalExamLabel.setText("Final Exam");
        finalExamLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        resultLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        resultLabel.setText("Result");
        resultLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        gradeOneTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        gradeOneTF.setPreferredSize(new java.awt.Dimension(200, 30));
        gradeOneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeOneTFActionPerformed(evt);
            }
        });
        gradeOneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gradeOneTFKeyTyped(evt);
            }
        });

        gradeTwoTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        gradeTwoTF.setPreferredSize(new java.awt.Dimension(200, 30));
        gradeTwoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gradeTwoTFKeyTyped(evt);
            }
        });

        gradeThreeTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        gradeThreeTF.setPreferredSize(new java.awt.Dimension(200, 30));
        gradeThreeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeThreeTFActionPerformed(evt);
            }
        });
        gradeThreeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gradeThreeTFKeyTyped(evt);
            }
        });

        finalExamTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        finalExamTF.setPreferredSize(new java.awt.Dimension(200, 30));
        finalExamTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                finalExamTFKeyTyped(evt);
            }
        });

        resultTF.setEditable(false);
        resultTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        resultTF.setForeground(new java.awt.Color(0, 0, 0));
        resultTF.setPreferredSize(new java.awt.Dimension(200, 30));

        logoHeadingLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        logoHeadingLabel.setForeground(new java.awt.Color(0, 0, 0));
        logoHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoHeadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/caglar/finalprojectaws/Images/gti-logo.png"))); // NOI18N
        logoHeadingLabel.setText("Record-Keeping System Further Education College");
        logoHeadingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoHeadingLabel.setIconTextGap(8);
        logoHeadingLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        studentIDLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        studentIDLabel.setText("Student ID");

        studentIDTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        studentIDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIDTFKeyTyped(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setText("*");
        warningLabel.setToolTipText("Please, Fill the all fields to add and update grade");
        warningLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        warningLabel.setPreferredSize(new java.awt.Dimension(8, 30));

        searchBTN.setBackground(new java.awt.Color(0, 153, 153));
        searchBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        searchBTN.setForeground(new java.awt.Color(255, 255, 255));
        searchBTN.setText("Search by Id");
        searchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBTNMouseExited(evt);
            }
        });
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        fullnameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fullnameLabel.setText("Fullname");
        fullnameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        fullnameTF.setEditable(false);
        fullnameTF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fullnameTF.setForeground(new java.awt.Color(0, 0, 0));
        fullnameTF.setPreferredSize(new java.awt.Dimension(200, 30));
        fullnameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullnameTFKeyTyped(evt);
            }
        });

        studenInfoBTN.setBackground(new java.awt.Color(0, 153, 153));
        studenInfoBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        studenInfoBTN.setForeground(new java.awt.Color(255, 255, 255));
        studenInfoBTN.setText("Student Info");
        studenInfoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studenInfoBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studenInfoBTNMouseExited(evt);
            }
        });
        studenInfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studenInfoBTNActionPerformed(evt);
            }
        });

        classGroupFrame.setBackground(new java.awt.Color(0, 153, 153));
        classGroupFrame.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        classGroupFrame.setForeground(new java.awt.Color(255, 255, 255));
        classGroupFrame.setText("Class Groups");
        classGroupFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                classGroupFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                classGroupFrameMouseExited(evt);
            }
        });
        classGroupFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classGroupFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherPanelLayout = new javax.swing.GroupLayout(teacherPanel);
        teacherPanel.setLayout(teacherPanelLayout);
        teacherPanelLayout.setHorizontalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logoHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(subjectCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teacherPanelLayout.createSequentialGroup()
                                    .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fullnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(finalExamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(firstGradeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(secondGradeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(thirdGradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studenInfoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(41, 41, 41)
                                    .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultTF, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(gradeThreeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(finalExamTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gradeTwoTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gradeOneTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentIDTF)
                                        .addComponent(fullnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(teacherPanelLayout.createSequentialGroup()
                                .addComponent(classGroupFrame)
                                .addGap(18, 18, 18)
                                .addComponent(updateGradeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        teacherPanelLayout.setVerticalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(logoHeadingLabel)
                .addGap(32, 32, 32)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBTN)
                    .addComponent(studenInfoBTN))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeThreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalExamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBTN)
                    .addComponent(updateGradeBTN)
                    .addComponent(classGroupFrame))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCBActionPerformed
        clearCB();
    }//GEN-LAST:event_subjectCBActionPerformed

    private void gradeThreeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeThreeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeThreeTFActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // to get the first word in the selected item, which is the subject_id
        String subjectFull = subjectCB.getSelectedItem().toString();
        String subject_id = subjectCB.getSelectedItem().toString().split(" ", 2)[0];
        String fullname = fullnameTF.getText();
        String student_id = studentIDTF.getText();

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "
                + student_id + " " + fullname + " from " + subjectFull);

        if (confirm == 0) {

            System.out.println("confirming delete");
            
            connect.deleteGrades(studentIDTF, subject_id, gradeOneTF, gradeTwoTF, gradeThreeTF, finalExamTF);
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void updateGradeBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateGradeBTNMouseEntered
        updateGradeBTN.setBackground(new Color(0, 204, 204));
        updateGradeBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_updateGradeBTNMouseEntered

    private void updateGradeBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateGradeBTNMouseExited
        updateGradeBTN.setBackground(new Color(0, 153, 153));
        updateGradeBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_updateGradeBTNMouseExited

    private void deleteBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseEntered
        deleteBTN.setBackground(new Color(0, 204, 204));
        deleteBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_deleteBTNMouseEntered

    private void deleteBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseExited
        deleteBTN.setBackground(new Color(0, 153, 153));
        deleteBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_deleteBTNMouseExited

    private void searchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseEntered
        searchBTN.setBackground(new Color(0, 204, 204));
        searchBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_searchBTNMouseEntered

    private void searchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseExited
        searchBTN.setBackground(new Color(0, 153, 153));
        searchBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_searchBTNMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        connect.selectSubject(subjectCB);
    }//GEN-LAST:event_formWindowOpened

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // Clear all TextField before setting them
        clearSearchBTN();
        // to get the first word in the selected item, which is the subject_id   
        String subject_id = subjectCB.getSelectedItem().toString().split(" ", 2)[0];
        // connecting to database and searching for studend and grades
        connect.searchStudent(studentIDTF, fullnameTF);
        connect.searchGrades(subject_id, studentIDTF, gradeOneTF, gradeTwoTF, gradeThreeTF, finalExamTF, resultTF);
    }//GEN-LAST:event_searchBTNActionPerformed

    private void gradeOneTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gradeOneTFKeyTyped
        DecimalDigitValidation(evt);
    }//GEN-LAST:event_gradeOneTFKeyTyped

    private void gradeTwoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gradeTwoTFKeyTyped
        DecimalDigitValidation(evt);
    }//GEN-LAST:event_gradeTwoTFKeyTyped

    private void gradeThreeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gradeThreeTFKeyTyped
        DecimalDigitValidation(evt);
    }//GEN-LAST:event_gradeThreeTFKeyTyped

    private void finalExamTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finalExamTFKeyTyped
        DecimalDigitValidation(evt);
    }//GEN-LAST:event_finalExamTFKeyTyped

    private void studentIDTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDTFKeyTyped
        DigitValidation(evt);
    }//GEN-LAST:event_studentIDTFKeyTyped

    private void updateGradeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGradeBTNActionPerformed
        // to get the first word in the selected item, which is the subject_id
        String subject_id = subjectCB.getSelectedItem().toString().split(" ", 2)[0];
        connect.updateGrades(studentIDTF, subject_id, gradeOneTF, gradeTwoTF, gradeThreeTF, finalExamTF);
    }//GEN-LAST:event_updateGradeBTNActionPerformed

    private void studenInfoBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenInfoBTNMouseEntered
        studenInfoBTN.setBackground(new Color(0, 204, 204));
        studenInfoBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_studenInfoBTNMouseEntered

    private void studenInfoBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenInfoBTNMouseExited
        studenInfoBTN.setBackground(new Color(0, 153, 153));
        studenInfoBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_studenInfoBTNMouseExited

    private void studenInfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studenInfoBTNActionPerformed
        if (!studentIDTF.getText().isEmpty()) {
        Student s1 = new Student(studentIDTF.getText());
        StudentInfoFrame stu = new StudentInfoFrame(s1);
        stu.setVisible(true);
        } else {
            searchBTN.requestFocus();
            DisplayMessage("Fill the Student ID");
        } 
    }//GEN-LAST:event_studenInfoBTNActionPerformed

    private void gradeOneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeOneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeOneTFActionPerformed

    private void classGroupFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classGroupFrameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_classGroupFrameMouseEntered

    private void classGroupFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classGroupFrameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_classGroupFrameMouseExited

    private void classGroupFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classGroupFrameActionPerformed
        TeacherClassGroupFrame classGroup = new TeacherClassGroupFrame();
        classGroup.setVisible(true);
    }//GEN-LAST:event_classGroupFrameActionPerformed

    private void fullnameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnameTFKeyTyped
        
    }//GEN-LAST:event_fullnameTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classGroupFrame;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel finalExamLabel;
    private javax.swing.JTextField finalExamTF;
    private javax.swing.JLabel firstGradeLabel;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JTextField fullnameTF;
    private javax.swing.JTextField gradeOneTF;
    private javax.swing.JTextField gradeThreeTF;
    private javax.swing.JTextField gradeTwoTF;
    private javax.swing.JLabel logoHeadingLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel secondGradeLabel;
    private javax.swing.JButton studenInfoBTN;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIDTF;
    private javax.swing.JComboBox<String> subjectCB;
    private javax.swing.JPanel teacherPanel;
    private javax.swing.JLabel thirdGradeLabel;
    private javax.swing.JButton updateGradeBTN;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
