package com.caglar.finalprojectaws.Views;

import com.caglar.finalprojectaws.Controllers.Controllers;
import com.caglar.finalprojectaws.Controllers.Database;
import com.caglar.finalprojectaws.Controllers.Teacher;
import static com.caglar.finalprojectaws.ValidationAndMethod.ValidationAndCalculation.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class TeacherInfoFrame extends javax.swing.JFrame {

    private Teacher id;
    private Connection con;
    private PreparedStatement prest;
    private Statement st;
    Controllers connect = new Controllers();

    public TeacherInfoFrame() {
        initComponents();
    }

    public TeacherInfoFrame(Teacher t1) {
        initComponents();
        this.id = t1;
        teacherIdTF.setText(t1.getTeacher_id());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherInfoPanel = new javax.swing.JPanel();
        personalInfoPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        teacherIdLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        ppsnLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        teacherIdTF = new javax.swing.JTextField();
        firstNameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        ppsnTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        dobTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        contactDetailsPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        addressLineOneLabel = new javax.swing.JLabel();
        addressLineTwo = new javax.swing.JLabel();
        eircodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        addressLineOneTF = new javax.swing.JTextField();
        addressLineTwoTF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        eircodeTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        updateTeacherDetailsBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Info Frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        teacherInfoPanel.setBackground(new java.awt.Color(239, 240, 234));

        personalInfoPanel.setBackground(new java.awt.Color(239, 240, 234));
        personalInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Info"));

        firstNameLabel.setText("First Name");
        firstNameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        surnameLabel.setText("Surname");
        surnameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        teacherIdLabel.setText("Teacher ID");
        teacherIdLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        passwordLabel.setText("Password");
        passwordLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        ppsnLabel.setText("PPSN");
        ppsnLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        genderLabel.setText("Gender");
        genderLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        dobLabel.setText("Date of Birth");
        dobLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        teacherIdTF.setPreferredSize(new java.awt.Dimension(200, 30));
        teacherIdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teacherIdTFKeyTyped(evt);
            }
        });

        firstNameTF.setPreferredSize(new java.awt.Dimension(200, 30));
        firstNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTFKeyTyped(evt);
            }
        });

        surnameTF.setPreferredSize(new java.awt.Dimension(200, 30));
        surnameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnameTFKeyTyped(evt);
            }
        });

        ppsnTF.setPreferredSize(new java.awt.Dimension(200, 30));
        ppsnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppsnTFKeyTyped(evt);
            }
        });

        genderTF.setPreferredSize(new java.awt.Dimension(200, 30));
        genderTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genderTFKeyTyped(evt);
            }
        });

        dobTF.setPreferredSize(new java.awt.Dimension(200, 30));
        dobTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobTFKeyTyped(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(0, 153, 153));
        searchBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        searchBTN.setForeground(new java.awt.Color(255, 255, 255));
        searchBTN.setText("Search by Id");
        searchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBTNMouseExited(evt);
            }
        });
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        passwordField.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(searchBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchBTN)
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ppsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ppsnTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contactDetailsPanel.setBackground(new java.awt.Color(239, 240, 234));
        contactDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));

        emailLabel.setText("E-mail");
        emailLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        phoneNumberLabel.setText("Phone Number");
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        addressLineOneLabel.setText("Address Line One");
        addressLineOneLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        addressLineTwo.setText("Address Line Two");
        addressLineTwo.setPreferredSize(new java.awt.Dimension(100, 30));

        eircodeLabel.setText("Eircode");
        eircodeLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        cityLabel.setText("City");
        cityLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        emailTF.setPreferredSize(new java.awt.Dimension(300, 30));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });
        emailTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTFKeyTyped(evt);
            }
        });

        phoneNumberTF.setPreferredSize(new java.awt.Dimension(300, 30));
        phoneNumberTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberTFKeyTyped(evt);
            }
        });

        addressLineOneTF.setPreferredSize(new java.awt.Dimension(300, 30));
        addressLineOneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressLineOneTFKeyTyped(evt);
            }
        });

        addressLineTwoTF.setPreferredSize(new java.awt.Dimension(300, 30));
        addressLineTwoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressLineTwoTFKeyTyped(evt);
            }
        });

        cityTF.setPreferredSize(new java.awt.Dimension(300, 30));
        cityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTFActionPerformed(evt);
            }
        });
        cityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityTFKeyTyped(evt);
            }
        });

        eircodeTF.setPreferredSize(new java.awt.Dimension(300, 30));
        eircodeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eircodeTFKeyTyped(evt);
            }
        });

        deleteBTN.setBackground(new java.awt.Color(0, 153, 153));
        deleteBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(255, 255, 255));
        deleteBTN.setText("Delete Current Teacher");
        deleteBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBTNMouseExited(evt);
            }
        });
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        updateTeacherDetailsBTN.setBackground(new java.awt.Color(0, 153, 153));
        updateTeacherDetailsBTN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        updateTeacherDetailsBTN.setForeground(new java.awt.Color(255, 255, 255));
        updateTeacherDetailsBTN.setText("Update Teacher Details");
        updateTeacherDetailsBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateTeacherDetailsBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateTeacherDetailsBTNMouseExited(evt);
            }
        });
        updateTeacherDetailsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherDetailsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactDetailsPanelLayout = new javax.swing.GroupLayout(contactDetailsPanel);
        contactDetailsPanel.setLayout(contactDetailsPanelLayout);
        contactDetailsPanelLayout.setHorizontalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(eircodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eircodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(addressLineTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(addressLineOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateTeacherDetailsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        contactDetailsPanelLayout.setVerticalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateTeacherDetailsBTN)
                .addGap(18, 18, 18)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                                                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(addressLineOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressLineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addressLineTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressLineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eircodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eircodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teacherInfoPanelLayout = new javax.swing.GroupLayout(teacherInfoPanel);
        teacherInfoPanel.setLayout(teacherInfoPanelLayout);
        teacherInfoPanelLayout.setHorizontalGroup(
            teacherInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherInfoPanelLayout.createSequentialGroup()
                .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        teacherInfoPanelLayout.setVerticalGroup(
            teacherInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personalInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseEntered
        searchBTN.setBackground(new Color(0, 204, 204));
        searchBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_searchBTNMouseEntered

    private void searchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseExited
        searchBTN.setBackground(new Color(0, 153, 153));
        searchBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_searchBTNMouseExited

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // to clean all TF
        firstNameTF.setText("");
        surnameTF.setText("");
        passwordField.setText("");
        ppsnTF.setText("");
        genderTF.setText("");
        dobTF.setText("");
        emailTF.setText("");
        phoneNumberTF.setText("");
        addressLineOneTF.setText("");
        addressLineTwoTF.setText("");
        cityTF.setText("");
        eircodeTF.setText("");

        connect.searchTeacher(teacherIdTF, firstNameTF, surnameTF, passwordField, ppsnTF, genderTF, dobTF, emailTF, phoneNumberTF,
                addressLineOneTF, addressLineTwoTF, cityTF, eircodeTF);
    }//GEN-LAST:event_searchBTNActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void updateTeacherDetailsBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTeacherDetailsBTNMouseEntered
        updateTeacherDetailsBTN.setBackground(new Color(0, 204, 204));
        updateTeacherDetailsBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_updateTeacherDetailsBTNMouseEntered

    private void updateTeacherDetailsBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTeacherDetailsBTNMouseExited
        updateTeacherDetailsBTN.setBackground(new Color(0, 153, 153));
        updateTeacherDetailsBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_updateTeacherDetailsBTNMouseExited

    private void updateTeacherDetailsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherDetailsBTNActionPerformed
        if (!(firstNameTF.getText().toString().isEmpty() || surnameTF.getText().toString().isEmpty())) {
            connect.updateTeacherDetail(teacherIdTF, firstNameTF, surnameTF, passwordField, ppsnTF, genderTF, dobTF, emailTF,
                    phoneNumberTF, addressLineOneTF, addressLineTwoTF, cityTF, eircodeTF);
        } else {
            DisplayMessage("Fill at least first name and sur name");
        }
    }//GEN-LAST:event_updateTeacherDetailsBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        Teacher t1 = new Teacher(teacherIdTF.getText().toString());
        t1.setFirst_name(firstNameTF.getText().toString());
        t1.setSur_name(surnameTF.getText().toString());
        t1.setFull_name(t1.getFirst_name() + " " + t1.getSur_name());

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "
                + t1.getTeacher_id() + " " + t1.getFull_name() + " from GTI Teacher record");

        if (confirm == 0) {
            
        //Database connection
        try {
            String url = "jdbc:mysql://" + Database.host + ":" + Database.port + "/" + Database.databaseName;
            con = DriverManager.getConnection(url, Database.userName, Database.password);
            System.out.println("connected");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

            try {
                String sql = "DELETE FROM teacher WHERE teacher_id = ?";
                prest = con.prepareStatement(sql);
                prest.setString(1, t1.getTeacher_id());

                int del = prest.executeUpdate();

                if (del > 0) {
                    DisplayMessage("✅ " + t1.getFull_name() + " deleted successfully!");
                } else {
                    DisplayMessage("⚠ No record found for this student and subject.");
                }
            } catch (SQLException e) {
                System.err.println("❌ Database error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void deleteBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseExited
        deleteBTN.setBackground(new Color(0, 153, 153));
        deleteBTN.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_deleteBTNMouseExited

    private void deleteBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseEntered
        deleteBTN.setBackground(new Color(0, 204, 204));
        deleteBTN.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_deleteBTNMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (!teacherIdTF.getText().isEmpty()){
        connect.searchTeacher(teacherIdTF, firstNameTF, surnameTF, passwordField, ppsnTF, genderTF,
                dobTF, emailTF, phoneNumberTF, addressLineOneTF, addressLineTwoTF, cityTF, eircodeTF);
        } 
    }//GEN-LAST:event_formWindowOpened

    private void teacherIdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacherIdTFKeyTyped
        DigitValidation(evt);
    }//GEN-LAST:event_teacherIdTFKeyTyped

    private void firstNameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_firstNameTFKeyTyped

    private void surnameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_surnameTFKeyTyped

    private void ppsnTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppsnTFKeyTyped
        LetterOrDigitValidation(evt);
    }//GEN-LAST:event_ppsnTFKeyTyped

    private void genderTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_genderTFKeyTyped

    private void dobTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobTFKeyTyped
        dateValidation(evt);
    }//GEN-LAST:event_dobTFKeyTyped

    private void emailTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTFKeyTyped
        emailValidation(evt, emailTF);
    }//GEN-LAST:event_emailTFKeyTyped

    private void phoneNumberTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberTFKeyTyped
        DigitValidation(evt);
    }//GEN-LAST:event_phoneNumberTFKeyTyped

    private void addressLineOneTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressLineOneTFKeyTyped
        LetterOrDigitOrSpaceValidation(evt);
    }//GEN-LAST:event_addressLineOneTFKeyTyped

    private void addressLineTwoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressLineTwoTFKeyTyped
        LetterOrDigitOrSpaceValidation(evt);
    }//GEN-LAST:event_addressLineTwoTFKeyTyped

    private void cityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTFActionPerformed

    private void cityTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTFKeyTyped
        LetterValidation(evt);
    }//GEN-LAST:event_cityTFKeyTyped

    private void eircodeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eircodeTFKeyTyped
        LetterOrDigitValidation(evt);
    }//GEN-LAST:event_eircodeTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLineOneLabel;
    private javax.swing.JTextField addressLineOneTF;
    private javax.swing.JLabel addressLineTwo;
    private javax.swing.JTextField addressLineTwoTF;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTF;
    private javax.swing.JPanel contactDetailsPanel;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel eircodeLabel;
    private javax.swing.JTextField eircodeTF;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTF;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTF;
    private javax.swing.JLabel ppsnLabel;
    private javax.swing.JTextField ppsnTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTF;
    private javax.swing.JLabel teacherIdLabel;
    private javax.swing.JTextField teacherIdTF;
    private javax.swing.JPanel teacherInfoPanel;
    private javax.swing.JButton updateTeacherDetailsBTN;
    // End of variables declaration//GEN-END:variables
}
